"""
ReportGenerator — produces JSON and HTML reports from QA run results.

The HTML report is a self-contained static file with embedded styles.
No separate frontend build is needed — it's generated by Jinja2 from a template.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

import aiofiles
from jinja2 import Environment, select_autoescape, FileSystemLoader

from qa_agent.utils.logger import get_logger
from qa_agent.utils.schemas import QARunResult, Severity

logger = get_logger(__name__)


class ReportGenerator:
    """
    Generates structured QA reports in JSON and HTML format.
    """

    def __init__(self, reports_dir: Path):
        self.reports_dir = reports_dir
        self.reports_dir.mkdir(parents=True, exist_ok=True)

        # Try to load Jinja2 templates from the package
        templates_dir = Path(__file__).parent / "templates"
        if templates_dir.exists():
            self._jinja_env = Environment(
                loader=FileSystemLoader(str(templates_dir)),
                autoescape=select_autoescape(["html"]),
            )
        else:
            self._jinja_env = None

    async def generate_json(self, result: QARunResult) -> str:
        """Generate machine-readable JSON report."""
        path = self.reports_dir / "report.json"

        # Mark completion time
        if not result.completed_at:
            result.completed_at = datetime.now(timezone.utc).isoformat()

        data = result.model_dump()
        # Sort findings by severity for readability
        data["findings"] = sorted(
            data["findings"],
            key=lambda f: {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3, "INFO": 4}.get(
                f.get("severity", "INFO"), 5
            ),
        )

        async with aiofiles.open(path, "w", encoding="utf-8") as f:
            await f.write(json.dumps(data, indent=2, ensure_ascii=False, default=str))

        logger.info(f"JSON report saved: {path}")
        return str(path)

    async def generate_html(self, result: QARunResult) -> str:
        """Generate human-readable HTML report."""
        path = self.reports_dir / "report.html"

        if self._jinja_env:
            try:
                template = self._jinja_env.get_template("report.html")
                html = template.render(result=result, severity=Severity)
            except Exception as e:
                logger.warning(f"Template rendering failed: {e}. Using built-in template.")
                html = self._generate_html_inline(result)
        else:
            html = self._generate_html_inline(result)

        async with aiofiles.open(path, "w", encoding="utf-8") as f:
            await f.write(html)

        logger.info(f"HTML report saved: {path}")
        return str(path)

    async def generate_excel(self, result: QARunResult) -> str:
        """Generate formatted Excel (.xlsx) report with multiple sheets."""
        try:
            import openpyxl
            from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
            from openpyxl.utils import get_column_letter
        except ImportError:
            logger.warning("openpyxl is not installed. Skipping Excel report generation.")
            return ""

        path = self.reports_dir / "report.xlsx"
        wb = openpyxl.Workbook()
        
        # Styles
        header_fill = PatternFill(start_color="1E40AF", end_color="1E40AF", fill_type="solid")
        header_font = Font(name="Calibri", size=11, bold=True, color="FFFFFF")
        title_font = Font(name="Calibri", size=16, bold=True, color="1E40AF")
        bold_font = Font(name="Calibri", size=11, bold=True)
        regular_font = Font(name="Calibri", size=11)
        
        sev_fills = {
            "CRITICAL": PatternFill(start_color="FEE2E2", end_color="FEE2E2", fill_type="solid"),
            "HIGH": PatternFill(start_color="FFEDD5", end_color="FFEDD5", fill_type="solid"),
            "MEDIUM": PatternFill(start_color="FEF3C7", end_color="FEF3C7", fill_type="solid"),
            "LOW": PatternFill(start_color="DBEAFE", end_color="DBEAFE", fill_type="solid"),
            "INFO": PatternFill(start_color="F3F4F6", end_color="F3F4F6", fill_type="solid"),
        }

        # Sheet 1: Executive Summary
        ws1 = wb.active
        ws1.title = "Executive Overview"
        ws1.views.sheetView[0].showGridLines = True
        
        ws1.cell(row=1, column=1, value="Autonomous QA Audit — Executive Summary").font = title_font
        
        overview_data = [
            ("Target URL", result.target_url),
            ("Run ID", result.run_id),
            ("Execution Duration", f"{result.duration_seconds:.1f}s" if result.duration_seconds else "N/A"),
            ("Perfection Score", f"{result.perfection_score}% ({result.perfection_rating})"),
            ("Pages Discovered", result.pages_discovered),
            ("States Tested", result.states_tested),
            ("Actions Performed", result.actions_performed),
            ("Viewports Tested", result.viewports_tested),
            ("Website Purpose", self.get_site_purpose(result.target_url)),
        ]
        
        for r_idx, (label, val) in enumerate(overview_data, start=3):
            c1 = ws1.cell(row=r_idx, column=1, value=label)
            c1.font = bold_font
            c2 = ws1.cell(row=r_idx, column=2, value=val)
            c2.font = regular_font

        # Findings Summary Table
        ws1.cell(row=14, column=1, value="Defect Severity Breakdown").font = Font(name="Calibri", size=13, bold=True, color="1E40AF")
        headers = ["Severity", "Count", "Description / Weight"]
        for c_idx, h in enumerate(headers, start=1):
            cell = ws1.cell(row=15, column=c_idx, value=h)
            cell.fill = header_fill
            cell.font = header_font
            
        sev_counts = [
            ("CRITICAL", result.critical_count, "-15 points per defect"),
            ("HIGH", result.high_count, "-8 points per defect"),
            ("MEDIUM", result.medium_count, "-3 points per defect"),
            ("LOW", result.low_count, "-1 point per defect"),
            ("INFO", sum(1 for f in result.findings if f.severity == Severity.INFO), "Informational audit notes"),
        ]
        for r_offset, (sev_name, count, desc) in enumerate(sev_counts, start=16):
            c1 = ws1.cell(row=r_offset, column=1, value=sev_name)
            c1.font = bold_font
            if sev_name in sev_fills:
                c1.fill = sev_fills[sev_name]
            c2 = ws1.cell(row=r_offset, column=2, value=count)
            c2.font = regular_font
            c3 = ws1.cell(row=r_offset, column=3, value=desc)
            c3.font = regular_font

        # Sheet 2: Defect Inventory
        ws2 = wb.create_sheet(title="Defect Inventory")
        ws2.views.sheetView[0].showGridLines = True
        
        def_headers = ["Bug ID", "Severity", "Category", "Title", "URL", "Viewport", "Expected", "Actual", "Reproduced"]
        for c_idx, h in enumerate(def_headers, start=1):
            cell = ws2.cell(row=1, column=c_idx, value=h)
            cell.fill = header_fill
            cell.font = header_font
            
        for r_idx, f in enumerate(result.findings, start=2):
            ws2.cell(row=r_idx, column=1, value=f.id).font = bold_font
            c_sev = ws2.cell(row=r_idx, column=2, value=f.severity.value)
            c_sev.font = bold_font
            if f.severity.value in sev_fills:
                c_sev.fill = sev_fills[f.severity.value]
            ws2.cell(row=r_idx, column=3, value=f.category.value).font = regular_font
            ws2.cell(row=r_idx, column=4, value=f.title).font = regular_font
            ws2.cell(row=r_idx, column=5, value=f.url).font = regular_font
            ws2.cell(row=r_idx, column=6, value=f.viewport).font = regular_font
            ws2.cell(row=r_idx, column=7, value=f.expected).font = regular_font
            ws2.cell(row=r_idx, column=8, value=f.actual).font = regular_font
            repro_str = "Yes" if f.reproduced is True else ("No" if f.reproduced is False else "N/A")
            ws2.cell(row=r_idx, column=9, value=repro_str).font = regular_font

        # Sheet 3: Actionable Enhancements
        ws3 = wb.create_sheet(title="Actionable Enhancements")
        ws3.views.sheetView[0].showGridLines = True
        
        enh_headers = ["Category", "Priority", "Recommended Action", "Business & Technical Impact"]
        for c_idx, h in enumerate(enh_headers, start=1):
            cell = ws3.cell(row=1, column=c_idx, value=h)
            cell.fill = header_fill
            cell.font = header_font
            
        enhancements = self.get_actionable_enhancements(result)
        for r_idx, enh in enumerate(enhancements, start=2):
            ws3.cell(row=r_idx, column=1, value=enh["category"]).font = bold_font
            c_prio = ws3.cell(row=r_idx, column=2, value=enh["priority"])
            c_prio.font = bold_font
            if enh["priority"] in sev_fills:
                c_prio.fill = sev_fills[enh["priority"]]
            ws3.cell(row=r_idx, column=3, value=enh["recommendation"]).font = regular_font
            ws3.cell(row=r_idx, column=4, value=enh["impact"]).font = regular_font

        # Auto-adjust column widths
        for sheet in wb.worksheets:
            for col in sheet.columns:
                max_len = max(len(str(cell.value or "")) for cell in col)
                col_letter = get_column_letter(col[0].column)
                sheet.column_dimensions[col_letter].width = min(max(max_len + 3, 12), 60)

        wb.save(path)
        logger.info(f"Excel report saved: {path}")
        return str(path)

    async def generate_docx(self, result: QARunResult) -> str:
        """Generate formatted Word (.docx) report."""
        try:
            import docx
            from docx.shared import Inches, Pt, RGBColor
            from docx.enum.text import WD_ALIGN_PARAGRAPH
            from docx.oxml import OxmlElement, parse_xml
            from docx.oxml.ns import nsdecls, qn
        except ImportError:
            logger.warning("python-docx is not installed. Skipping Word report generation.")
            return ""

        path = self.reports_dir / "report.docx"
        doc = docx.Document()

        # Title
        title_p = doc.add_paragraph()
        title_run = title_p.add_run("Autonomous QA Audit & Site Perfection Report")
        title_run.font.name = "Arial"
        title_run.font.size = Pt(20)
        title_run.font.bold = True
        title_run.font.color.rgb = RGBColor(30, 64, 175)

        sub_p = doc.add_paragraph()
        sub_run = sub_p.add_run(f"Target URL: {result.target_url}  |  Run ID: {result.run_id}")
        sub_run.font.size = Pt(11)
        sub_run.font.color.rgb = RGBColor(100, 116, 139)

        doc.add_heading("1. Executive Overview & Perfection Score", level=1)
        
        p = doc.add_paragraph()
        p.add_run("Overall Perfection Score: ").bold = True
        score_run = p.add_run(f"{result.perfection_score}% ({result.perfection_rating})\n")
        score_run.bold = True
        score_run.font.size = Pt(14)
        if result.perfection_score >= 85:
            score_run.font.color.rgb = RGBColor(22, 163, 74)
        elif result.perfection_score >= 70:
            score_run.font.color.rgb = RGBColor(217, 119, 6)
        else:
            score_run.font.color.rgb = RGBColor(220, 38, 38)
            
        p.add_run(f"Execution Duration: {result.duration_seconds:.1f}s\n" if result.duration_seconds else "")
        p.add_run(f"Pages Discovered: {result.pages_discovered}  |  States Tested: {result.states_tested}  |  Actions Performed: {result.actions_performed}\n")
        p.add_run(f"Viewports Tested: {result.viewports_tested} (Desktop, Laptop, Tablet, Mobile)\n")

        doc.add_heading("2. Website Purpose & Scope", level=1)
        doc.add_paragraph(self.get_site_purpose(result.target_url))

        doc.add_heading("3. Actionable Enhancement Recommendations", level=1)
        enhancements = self.get_actionable_enhancements(result)
        for enh in enhancements:
            p_enh = doc.add_paragraph(style='List Bullet')
            r_cat = p_enh.add_run(f"[{enh['category']}] (Priority: {enh['priority']}): ")
            r_cat.bold = True
            p_enh.add_run(f"{enh['recommendation']} ")
            r_imp = p_enh.add_run(f"Impact: {enh['impact']}")
            r_imp.font.italic = True

        doc.add_heading("4. Detected Defect Inventory", level=1)
        if not result.findings:
            doc.add_paragraph("No defects were detected during this audit run. The site passed all automated checks!")
        else:
            table = doc.add_table(rows=1, cols=5)
            table.style = 'Table Grid'
            hdr_cells = table.rows[0].cells
            headers = ["Bug ID", "Severity", "Category", "Title & Summary", "Reproduced"]
            for idx, h in enumerate(headers):
                hdr_cells[idx].text = h
                hdr_cells[idx].paragraphs[0].runs[0].font.bold = True

            for f in result.findings:
                row_cells = table.add_row().cells
                row_cells[0].text = f.id
                row_cells[1].text = f.severity.value
                row_cells[2].text = f.category.value
                row_cells[3].text = f"{f.title}\n{f.description[:120]}..."
                row_cells[4].text = "Yes" if f.reproduced is True else ("No" if f.reproduced is False else "N/A")

        doc.save(path)
        logger.info(f"Word report saved: {path}")
        return str(path)

    def get_site_purpose(self, target_url: str) -> str:
        """Infer website purpose from URL."""
        url_lower = target_url.lower()
        if "youtube" in url_lower:
            return "YouTube is the world's premier video sharing, streaming, and content platform designed for global media distribution, creator monetization, live broadcasting, and user community interaction."
        elif "example.com" in url_lower:
            return "Example.com is an illustrative reference domain managed by IANA for documentation, standard compliance verification, and baseline web software testing."
        elif "localhost" in url_lower or "127.0.0.1" in url_lower:
            return "Local web application under active software development, testing, and continuous quality integration."
        else:
            return f"Digital web application hosted at {target_url} providing online services, content delivery, and interactive user experiences."

    def get_actionable_enhancements(self, result: QARunResult) -> list[dict]:
        """Generate strategic enhancement recommendations from findings."""
        enhancements = []
        
        console_findings = [f for f in result.findings if f.category.value == "CONSOLE"]
        if console_findings:
            enhancements.append({
                "category": "Console & JS Stability",
                "priority": "HIGH",
                "recommendation": "Resolve client-side JavaScript console errors (e.g. unauthenticated 401 calls or net::ERR_NAME_NOT_RESOLVED dependencies) to avoid runtime script failures.",
                "impact": "Improves web application stability and prevents unexpected frontend crashes."
            })
            
        network_findings = [f for f in result.findings if f.category.value == "NETWORK"]
        if network_findings:
            enhancements.append({
                "category": "Network & API Reliability",
                "priority": "HIGH",
                "recommendation": "Fix HTTP 401/403 access control errors on media pre-fetch endpoints. Implement error boundaries and retry logic for aborted requests.",
                "impact": "Ensures seamless API data fetching and continuous video playback."
            })

        image_findings = [f for f in result.findings if f.category.value == "IMAGE"]
        if image_findings:
            enhancements.append({
                "category": "Image & Asset Optimization",
                "priority": "MEDIUM",
                "recommendation": "Add alt attributes to unannotated images and implement lazy-loading placeholders for unrendered media thumbnails.",
                "impact": "Boosts accessibility compliance and prevents empty image layouts."
            })

        accessibility_findings = [f for f in result.findings if f.category.value == "ACCESSIBILITY"]
        if accessibility_findings:
            enhancements.append({
                "category": "Accessibility (WCAG 2.1)",
                "priority": "HIGH",
                "recommendation": "Incorporate landmark tags (<main>, <nav>), enforce sequential heading tag hierarchy (H1 -> H2), and configure TrustedScriptURL policy for dynamic scripts.",
                "impact": "Achieves full WCAG 2.1 compliance for screen-reader users."
            })

        layout_findings = [f for f in result.findings if f.category.value in ["LAYOUT", "RESPONSIVE", "VISUAL"]]
        if layout_findings:
            enhancements.append({
                "category": "Responsive Layout UX",
                "priority": "HIGH",
                "recommendation": "Eliminate horizontal viewport overflow on mobile sizes (390x844) and fix overlapping z-index boundaries on navigation elements.",
                "impact": "Delivers a seamless visual layout experience across all device form factors."
            })

        if not enhancements:
            enhancements.append({
                "category": "General Quality Maintenance",
                "priority": "LOW",
                "recommendation": "No defects detected. Maintain continuous automated regression testing.",
                "impact": "Sustains 100% perfection rating."
            })

        return enhancements

    def _generate_html_inline(self, result: QARunResult) -> str:
        """
        Generate HTML report without Jinja2 template.
        Self-contained with embedded CSS — no external dependencies.
        """
        findings_by_severity = {
            "CRITICAL": [f for f in result.findings if f.severity == Severity.CRITICAL],
            "HIGH": [f for f in result.findings if f.severity == Severity.HIGH],
            "MEDIUM": [f for f in result.findings if f.severity == Severity.MEDIUM],
            "LOW": [f for f in result.findings if f.severity == Severity.LOW],
            "INFO": [f for f in result.findings if f.severity == Severity.INFO],
        }

        severity_colors = {
            "CRITICAL": "#dc2626",
            "HIGH": "#ea580c",
            "MEDIUM": "#d97706",
            "LOW": "#2563eb",
            "INFO": "#6b7280",
        }

        def severity_badge(sev: str) -> str:
            color = severity_colors.get(sev, "#6b7280")
            return f'<span style="background:{color};color:white;padding:2px 8px;border-radius:4px;font-size:12px;font-weight:bold">{sev}</span>'

        def finding_html(f) -> str:
            steps = "".join(f"<li>{s}</li>" for s in f.steps_to_reproduce)
            screenshot_html = ""
            if f.annotated_screenshot:
                rel = Path(f.annotated_screenshot).name
                screenshot_html += f'<img src="../screenshots/{rel}" style="max-width:100%;border:1px solid #e5e7eb;border-radius:4px;margin-top:8px" alt="{f.id} annotated screenshot">'
            elif f.screenshot:
                rel = Path(f.screenshot).name
                screenshot_html += f'<img src="../screenshots/{rel}" style="max-width:100%;border:1px solid #e5e7eb;border-radius:4px;margin-top:8px" alt="{f.id} screenshot">'

            reproduced_html = ""
            if f.reproduced is True:
                reproduced_html = '<span style="color:#16a34a">✓ Reproduced</span>'
            elif f.reproduced is False:
                reproduced_html = '<span style="color:#dc2626">✗ Could not reproduce</span>'
            else:
                reproduced_html = '<span style="color:#6b7280">— Not attempted</span>'

            return f"""
            <div style="border:1px solid #e5e7eb;border-radius:8px;padding:16px;margin:12px 0;background:#fff">
                <div style="display:flex;align-items:center;gap:12px;margin-bottom:8px">
                    <code style="font-size:13px;color:#6b7280">{f.id}</code>
                    {severity_badge(f.severity.value)}
                    <span style="font-size:12px;background:#f3f4f6;padding:2px 6px;border-radius:4px">{f.category.value}</span>
                    <span style="margin-left:auto;font-size:12px">{reproduced_html}</span>
                </div>
                <h3 style="margin:0 0 8px;font-size:16px">{f.title}</h3>
                <p style="margin:0 0 8px;color:#4b5563;font-size:14px;white-space:pre-line">{f.description}</p>
                <div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:8px 0;font-size:13px">
                    <div><strong>URL:</strong> <a href="{f.url}" target="_blank">{f.url[:80]}</a></div>
                    <div><strong>Viewport:</strong> {f.viewport}</div>
                    <div><strong>Expected:</strong> {f.expected[:100]}</div>
                    <div><strong>Actual:</strong> {f.actual[:100]}</div>
                    <div><strong>Confidence:</strong> {f.confidence:.0%}</div>
                    <div><strong>Timestamp:</strong> {f.timestamp[:19]}</div>
                </div>
                {"<div><strong>Steps to reproduce:</strong><ol style='margin:4px 0;font-size:13px'>" + steps + "</ol></div>" if steps else ""}
                {screenshot_html}
            </div>"""

        all_findings_html = ""
        for sev, sev_findings in findings_by_severity.items():
            if sev_findings:
                all_findings_html += f"""
                <h2 style="margin:24px 0 8px;color:{severity_colors[sev]}">{sev} ({len(sev_findings)})</h2>
                {"".join(finding_html(f) for f in sev_findings)}"""

        validators_html = "".join(
            f'<div style="display:flex;align-items:center;gap:8px;padding:4px 0">'
            f'<span style="color:{"#16a34a" if v not in result.validators_failed else "#dc2626"}">'
            f'{"✓" if v not in result.validators_failed else "✗"}</span>'
            f'<span>{v}</span></div>'
            for v in result.validators_run
        )

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>QA Report — {result.target_url}</title>
    <style>
        * {{ box-sizing: border-box; margin: 0; padding: 0; }}
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #f9fafb; color: #111827; line-height: 1.5; }}
        .container {{ max-width: 1100px; margin: 0 auto; padding: 24px; }}
        .header {{ background: linear-gradient(135deg, #1e40af, #3b82f6); color: white; padding: 32px; border-radius: 12px; margin-bottom: 24px; }}
        .header h1 {{ font-size: 24px; font-weight: 700; }}
        .header p {{ opacity: 0.85; margin-top: 4px; }}
        .stats-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr)); gap: 12px; margin-bottom: 24px; }}
        .stat-card {{ background: white; border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; text-align: center; }}
        .stat-card .value {{ font-size: 28px; font-weight: 700; }}
        .stat-card .label {{ font-size: 12px; color: #6b7280; margin-top: 4px; }}
        .section {{ background: white; border: 1px solid #e5e7eb; border-radius: 8px; padding: 20px; margin-bottom: 20px; }}
        a {{ color: #2563eb; text-decoration: none; }}
        a:hover {{ text-decoration: underline; }}
    </style>
</head>
<body>
<div class="container">
    <div class="header">
        <h1>Autonomous QA Report</h1>
        <p>{result.target_url}</p>
        <p style="margin-top:8px;font-size:13px;opacity:0.75">
            Run ID: {result.run_id} &nbsp;|&nbsp;
            Started: {result.started_at[:19]} &nbsp;|&nbsp;
            Duration: {f"{result.duration_seconds:.1f}s" if result.duration_seconds else "N/A"}
        </p>
    </div>

    <div class="stats-grid">
        <div class="stat-card"><div class="value">{result.pages_discovered}</div><div class="label">Pages Discovered</div></div>
        <div class="stat-card"><div class="value">{result.states_tested}</div><div class="label">States Tested</div></div>
        <div class="stat-card"><div class="value">{result.actions_performed}</div><div class="label">Actions</div></div>
        <div class="stat-card"><div class="value">{result.viewports_tested}</div><div class="label">Viewports</div></div>
        <div class="stat-card"><div class="value" style="color:#dc2626">{result.critical_count}</div><div class="label">Critical</div></div>
        <div class="stat-card"><div class="value" style="color:#ea580c">{result.high_count}</div><div class="label">High</div></div>
        <div class="stat-card"><div class="value" style="color:#d97706">{result.medium_count}</div><div class="label">Medium</div></div>
        <div class="stat-card"><div class="value" style="color:#2563eb">{result.low_count}</div><div class="label">Low</div></div>
        <div class="stat-card"><div class="value" style="color:#16a34a">{result.reproduced_count}</div><div class="label">Reproduced</div></div>
    </div>

    <div class="section">
        <h2 style="margin-bottom:12px">Validators Run</h2>
        {validators_html}
    </div>

    <div class="section">
        <h2 style="margin-bottom:4px">Findings ({result.total_issues} total)</h2>
        {all_findings_html if all_findings_html else '<p style="color:#6b7280;margin-top:12px">No issues detected.</p>'}
    </div>

    <p style="text-align:center;color:#9ca3af;font-size:12px;margin-top:24px">
        Generated by Autonomous Multimodal QA Agent v0.1.0 &nbsp;|&nbsp; {result.completed_at[:19] if result.completed_at else 'N/A'}
    </p>
</div>
</body>
</html>"""
